# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
default_platform(:android)
platform :android do
    desc "My awesome app"
    lane :distribute do
        build_android_app(
    project_dir: ".",
    flavor: "production",
    build_type: "Release"
        )
        # build_android_app is a built-in fastlane action.
        release = firebase_app_distribution(
            app: "1:765228054269:android:45b8e4c4e2b85e3321f094"
        )
    end
end
