name: Test, Build and Release ipa
on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
  workflow_dispatch:    
jobs:
  build:
    name: Build ipa
    runs-on: macos-latest
    steps:
    - uses: ruby/setup-ruby@v1
      with:
         ruby-version: '3.3'
         bundler-cache: true  
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 
        
    # - name: Set Timezone
    #   uses: szenius/set-timezone@v2.0
    #   with:
    #     timezoneLinux: "Asia/Kolkata"
    #     timezoneMacos: "Asia/Kolkata"  
        
    - name: Install Bundler
      run: gem install bundler     
      
    - name: Install gems
      run: bundle install
      
    - name: Set up Firebase CLI
      run: |
        curl -sL https://firebase.tools | bash  
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
        
    - name: Clone Flutter repository with master channel
      uses: subosito/flutter-action@2783a3f08e1baf891508463f8c6653c258246225
      with:
        channel: master
    # - run: flutter doctor -v
    # - run: flutter pub get
    # - run: flutter test
    - run: |

        flutter build ios --debug --no-codesign

    - name: Archive iOS app
      run: |
        mkdir -p build/ios/ipa
        xcrun -sdk iphoneos PackageApplication -v build/ios/iphoneos/Runner.app -o build/ios/ipa/Runner.ipa

    - name: Upload IPA
      uses: actions/upload-artifact@v3
      with:
        name: ipa
        path: build/ios/ipa/Runner.ipa
    # - name: Push ios to Releases
    #   uses: ncipollo/release-action@v1
    #   with:
    #     artifacts: "/build/ios/iphoneos/*.app"
    #     token: ${{ secrets.TOKEN }}
    #     tag: v1.0.${{ github.run_number }}    

    - name: Run Fastlane ios
      working-directory: ./ios
      run: |
        bundle exec fastlane ios distribute_ios --verbose 
      env:
        APP_ID: ${{ secrets.APP_ID_IOS }}
        FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}        
      #   GOOGLE_APPLICATION_CREDENTIALS: "./serviceaccount.json"         
